#!/usr/bin/lua


action = {
  ["cq"] = function (x) print("\r\n"); os.execute("reboot"); print("重启") end, 
  ["la"] = function (x) print("\r\n"); os.execute("/etc/config/lan.sh"); print("电脑拨号 设置成功") end, 
  ["wa"] = function (x) print("\r\n"); os.execute("/etc/config/wan.sh"); print("路由器---设置成功") end, 





}

action[string.sub(os.getenv("QUERY_STRING"),1,2)](string.sub(os.getenv("QUERY_STRING"),3,5))